### ISSUE TITLE
Obervable은 Observer를 구독

### ISSUE THREAD

**Issue by protocorn93** [ClintJang/sample-rxswift-beginning#1]
안녕하세요 클린트님 좋은 자료 잘 보며 공부하고 있습니다. 

다름이 아니라 리액티브 X 페이지에선  `ReactiveX에서 옵저버는 Observable을 구독한다. Obseravable이 배출하는 하나 또는 연속된 항목에 옵저버는 반응한다. ` 라고 나와있는데

README 본문에서 `Observable` 과 `Observer`의 문장 내 위치가 바뀌어

`ReactiveX에서 Observable은 Observer를 구독합니다. 그런 다음 Observer는 Observable Sequence에 따라 반응합니다.` 라고 나와있는데 이에 대해 이슈를 남겨봅니다 :)

**Comment by ClintJang** [comment]
너무 고맙습니다. 😀
저도 이제 RX 공부 시작했습니다. 이거이거 참 쉽지 않네요. 그래도 참 재미져요.
샘플링도 하다가 중지했는 데, 업데이트를 계속 해야겠군요 ~ 😓
바로 수정 해야겠네요. 감사합니다.🙇‍
